version: '3.1'

services:
  db:
    container_name: 'roomdb'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: roomser
      POSTGRES_PASSWORD: roompassword
      POSTGRES_DB: roomdb
    ports:
      - 5432:5432